# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc088997a068475e896dd629153a5fd42cc466639ede7fb94526134f6ce9b9deb72c887566c58fc0069074d2d9d8b634c75a8bbf530b71ea9ab5ed66653424f

test:
  secret_key_base: d3a4bad5403791bb69de330ea4e6ed62070dd325700dbcacba706da7617af16690bb260120b1670c8c51250edc5058664980e29c4609040f5315a6de79b70d34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
